# travis.yml
#test
sudo: required

language: php
env:
  # This environment variable tells Terraform not to prompt for input. This is
  # not required, but if we make a mistake, the Travis builder will hang waiting
  # for user input, tieing up unnecessary resources.
  - TF_INPUT=false
services:
   - docker

post_install:
  # Push docker image to Docker Hub

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - set aws_access_key_id $AWS_ACCESS_KEY
  - set aws_secret_access_key $AWS_SECRET_KEY
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.8.8/terraform_0.8.8_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  #- mkdir ~/bin
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

script:
  - terraform plan

deploy:
   # Deploy using terraform
  - provider: script
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    skip_cleanup: true
    script: terraform apply
    on:
      branch: master

