# travis.yml
#test
sudo: required

language: php

services:
   - docker

script:
  # Build docker image
  terraform plan ./terraform
post_install:
  # Push docker image to Docker Hub

before_deploy:
   # Install terraform§§
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.8.8/terraform_0.8.8_linux_amd64.zip
  - unzip terraform_0.8.8_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - export PATH="~/bin:$PATH"
  - terraform init
  - terraform plan
deploy:
   # Deploy using terraform
provider: script
  script:
  - terraform apply
  skip_cleanup: true
  on:
   branch: master

