# travis.yml
sudo: required
language: php
services:
  - docker
script:
  # Build docker image
  - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
  - unzip terraform_0.11.11_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - terraform init
  - terraform plan
  - terraform apply -auto-approve
post_install:
# Push docker image to Docker Hub
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker push waill/tp-42:tagname fi
  - docker pull waill/tp-42
before_deploy:
# Install terraform
deploy:
# Deploy using terraform