# travis.yml
#test
sudo: required

language: php

services:
   - docker

post_install:
  # Push docker image to Docker Hub

before_deploy:
   # Install terraform§§
    - wget https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
    - unzip terraform_0.10.6_linux_amd64.zip


script:
  - ./terraform init
  - ./terraform plan

deploy:
   # Deploy using terraform
  - provider: script
    skip_cleanup: true
    script: ./terraform apply
    on:
      branch: master



