sudo: required
language: php
env:
  - TF_INPUT=false
services:
   - docker
post_install:

script:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.8.8/terraform_0.8.8_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"
  - terraform init
  - terraform plan
  - terraform destroy -auto-approve

