# travis.yml
sudo: required
language: php
services:
  - docker
script:
  # Build docker image
  - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
  - unzip terraform_0.10.6_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - terraform init
  - terraform plan
  - terraform apply -input=false -auto-approve
post_install:
# Push docker image to Docker Hub

before_deploy:
# Install terraform
deploy:
# Deploy using terraform